version: 2
jobs:
  build:
    machine: true
    working_directory: ~/dokku/plugn
    parallelism: 1
    steps:
      - checkout
      - run: |
          sudo add-apt-repository ppa:longsleep/golang-backports -y
          sudo apt-get update
          sudo apt-get -y install golang-1.11
          ls -lah /usr/lib/ | grep go-
          go version
          make circleci
      - run: |
          make deps
      - run: |
          GO111MODULE=on make build
      - run: |
          tests/**/tests.sh
      - deploy:
          name: release
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              make release
            fi
